# Render Deployment Configuration
databases:
  - name: lead-qualification-db
    databaseName: lead_qualification_api
    user: lead_api_user

services:
  - type: web
    name: lead-qualification-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lead_qualification_api.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lead-qualification-db
          property: connectionString