# Generated by Django 4.2.7 on 2025-09-15 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin_bio', models.TextField(blank=True)),
                ('upload_batch', models.CharField(help_text='Batch identifier for uploaded leads', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_props', models.JSONField(help_text='List of value propositions')),
                ('ideal_use_cases', models.JSONField(help_text='List of ideal use cases/industries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_score', models.IntegerField(default=0, help_text='Score based on role relevance (0-20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('industry_score', models.IntegerField(default=0, help_text='Score based on industry match (0-20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('completeness_score', models.IntegerField(default=0, help_text='Score based on data completeness (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ai_score', models.IntegerField(default=0, help_text='Score from AI analysis (0-50)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('ai_intent', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='AI-determined intent level', max_length=10)),
                ('ai_reasoning', models.TextField(help_text='AI explanation for the scoring')),
                ('total_score', models.IntegerField(help_text='Total score (rule_score + ai_score)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('intent_label', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Final intent classification', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='qualification.lead')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.offer')),
            ],
            options={
                'ordering': ['-total_score', '-created_at'],
            },
        ),
    ]
